[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mongoose"
version = "0.0.1"
description = "error handling library"
readme = "README.md"
requires-python = ">=3.8"

